import React, { useState, useEffect, useRef } from 'react';
import { Code2, Play, CheckCircle, AlertCircle, RefreshCw, Copy, BookOpen, Zap, Settings } from 'lucide-react';

type Game = 'fo4' | 'sse' | 'le';
type RightTab = 'output' | 'snippets' | 'events';
interface Issue { line: number; severity: 'error'|'warning'|'info'; message: string; }
interface Snippet { title: string; code: string; category: string; }

const STARTER = `Scriptname MyQuest extends Quest\n\n; Auto-generated by Mossy AI\nActor Property PlayerRef Auto\n\nEvent OnInit()\n    Debug.Notification("Script initialized!")\nEndEvent\n`;

const PapyrusIDE: React.FC = () => {
  const [script, setScript] = useState(STARTER);
  const [scriptName, setScriptName] = useState('MyQuest');
  const [game, setGame] = useState<Game>('fo4');
  const [rightTab, setRightTab] = useState<RightTab>('output');
  const [issues, setIssues] = useState<Issue[]>([]);
  const [snippets, setSnippets] = useState<Snippet[]>([]);
  const [events, setEvents] = useState<Record<string, string[]>>({});
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [health, setHealth] = useState(false);
  const [stats, setStats] = useState({ functions: 0, properties: 0, events: 0, lines: 0 });
  const [valid, setValid] = useState<'unchecked'|'valid'|'invalid'>('unchecked');
  const [compilerPath, setCompilerPath] = useState('');
  const [showSettings, setShowSettings] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => { checkHealth(); loadSnippets(); loadEvents(); }, []);

  useEffect(() => {
    const lines = script.split('\n');
    setStats({
      lines: lines.length,
      functions: (script.match(/^Function\s/gm)||[]).length,
      properties: (script.match(/Property\s/g)||[]).length,
      events: (script.match(/^Event\s/gm)||[]).length,
    });
  }, [script]);

  const checkHealth = async () => {
    try { const r = await window.electronAPI?.ipcInvoke('papyrus:health-check'); setHealth(r?.status === 'healthy'); } catch { setHealth(false); }
  };

  const loadSnippets = async () => {
    try { const r = await window.electronAPI?.ipcInvoke('papyrus:snippet-library'); if (r?.snippets) setSnippets(r.snippets); } catch {}
  };

  const loadEvents = async () => {
    try { const r = await window.electronAPI?.ipcInvoke('papyrus:common-events'); if (r?.events) setEvents(r.events); } catch {}
  };

  const validate = async () => {
    setLoading(true); setRightTab('output'); setIssues([]);
    try {
      const r = await window.electronAPI?.ipcInvoke('papyrus:validate', { script_content: script, game });
      if (r?.issues) { setIssues(r.issues); setValid(r.valid ? 'valid' : 'invalid'); setOutput(`Validation complete — ${r.issues.length} issue(s)\nFunctions: ${r.stats?.functions} · Properties: ${r.stats?.properties} · Events: ${r.stats?.events}`); }
      else setOutput(r?.message || 'Validation failed');
    } catch (e: any) { setOutput(String(e)); }
    setLoading(false);
  };

  const compile = async () => {
    setLoading(true); setRightTab('output'); setIssues([]);
    try {
      const r = await window.electronAPI?.ipcInvoke('papyrus:compile', { script_content: script, script_name: scriptName, game });
      setOutput(r?.compiled ? `✓ Compiled successfully\n${r.output_path||''}` : `✗ Compile failed\n${r?.errors?.join('\n')||r?.message||''}`);
      if (r?.errors) setIssues((r.line_errors||[]).map((e: any) => ({ line: e.line, severity: 'error', message: e.message })));
      setValid(r?.compiled ? 'valid' : 'invalid');
    } catch (e: any) { setOutput(String(e)); }
    setLoading(false);
  };

  const insertSnippet = (code: string) => {
    const ta = textareaRef.current;
    if (!ta) return;
    const start = ta.selectionStart;
    setScript(prev => prev.slice(0, start) + '\n' + code + '\n' + prev.slice(start));
  };

  const copy = () => navigator.clipboard.writeText(script);
  const saveSettings = async () => {
    if (compilerPath) await window.electronAPI?.ipcInvoke('papyrus:set-compiler-path', { path: compilerPath });
    setShowSettings(false);
  };

  const severityColor = { error: 'text-red-400', warning: 'text-amber-400', info: 'text-blue-400' };
  const validColor = { unchecked: 'text-slate-500', valid: 'text-emerald-400', invalid: 'text-red-400' };

  return (
    <div className="h-full flex flex-col bg-forge-dark overflow-hidden">
      <div className="px-5 py-3 border-b border-slate-700 bg-forge-panel flex items-center gap-3 flex-wrap">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-emerald-500/20 rounded-lg border border-emerald-500/30"><Code2 className="w-4 h-4 text-emerald-400"/></div>
          <span className="font-bold text-white text-base">Papyrus IDE</span>
        </div>
        <input value={scriptName} onChange={e=>setScriptName(e.target.value)} className="bg-slate-800 border border-slate-700 rounded px-2 py-1 text-xs text-slate-200 w-40 focus:outline-none focus:border-emerald-500"/>
        <select value={game} onChange={e=>setGame(e.target.value as Game)} className="bg-slate-800 border border-slate-700 rounded px-2 py-1 text-xs text-slate-200 focus:outline-none focus:border-emerald-500">
          <option value="fo4">Fallout 4</option><option value="sse">Skyrim SE</option><option value="le">Skyrim LE</option>
        </select>
        <div className="flex gap-1.5 ml-auto flex-wrap">
          <button onClick={validate} disabled={loading} className="flex items-center gap-1 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white text-xs font-bold rounded-lg transition-colors">
            {loading?<RefreshCw className="w-3 h-3 animate-spin"/>:<CheckCircle className="w-3 h-3"/>} Validate
          </button>
          <button onClick={compile} disabled={loading} className="flex items-center gap-1 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-40 text-white text-xs font-bold rounded-lg transition-colors">
            {loading?<RefreshCw className="w-3 h-3 animate-spin"/>:<Play className="w-3 h-3"/>} Compile
          </button>
          <button onClick={copy} className="flex items-center gap-1 px-2.5 py-1.5 bg-slate-700 hover:bg-slate-600 text-white text-xs rounded-lg transition-colors"><Copy className="w-3 h-3"/></button>
          <button onClick={()=>setShowSettings(!showSettings)} className="flex items-center gap-1 px-2.5 py-1.5 bg-slate-700 hover:bg-slate-600 text-white text-xs rounded-lg transition-colors"><Settings className="w-3 h-3"/></button>
        </div>
      </div>

      {showSettings && (
        <div className="border-b border-slate-700 bg-slate-900 px-5 py-3 flex items-center gap-3">
          <input value={compilerPath} onChange={e=>setCompilerPath(e.target.value)} className="flex-1 bg-slate-800 border border-slate-700 rounded px-3 py-1.5 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-emerald-500" placeholder="PapyrusCompiler.exe path (optional — validator works without it)"/>
          <button onClick={saveSettings} className="px-3 py-1.5 bg-emerald-700 hover:bg-emerald-600 text-white text-xs font-bold rounded-lg transition-colors">Save</button>
        </div>
      )}

      <div className="flex-1 flex overflow-hidden">
        {/* Editor */}
        <div className="flex-1 flex flex-col overflow-hidden">
          <textarea
            ref={textareaRef}
            value={script}
            onChange={e=>setScript(e.target.value)}
            spellCheck={false}
            className="flex-1 bg-[#0d1117] text-emerald-200 font-mono text-sm p-4 resize-none focus:outline-none leading-relaxed"
            style={{ tabSize: 4 }}
          />
          {/* Stats bar */}
          <div className="bg-slate-900 border-t border-slate-800 px-4 py-1.5 flex items-center gap-4 text-[10px] text-slate-500 font-mono">
            <span className={`font-bold ${validColor[valid]}`}>{valid.toUpperCase()}</span>
            <span>Lines: {stats.lines}</span><span>Fn: {stats.functions}</span>
            <span>Prop: {stats.properties}</span><span>Event: {stats.events}</span>
            <span className="ml-auto">{health?'🟢 Compiler':'🔴 No Compiler'} · {game.toUpperCase()}</span>
          </div>
        </div>

        {/* Right panel */}
        <div className="w-80 border-l border-slate-800 flex flex-col overflow-hidden">
          <div className="flex border-b border-slate-800">
            {(['output','snippets','events'] as RightTab[]).map(t=>(
              <button key={t} onClick={()=>setRightTab(t)} className={`flex-1 py-2 text-[10px] font-bold uppercase tracking-widest transition-colors ${rightTab===t?'bg-slate-800 text-white':'text-slate-500 hover:text-slate-300'}`}>{t}</button>
            ))}
          </div>
          <div className="flex-1 overflow-y-auto p-3">
            {rightTab==='output' && (
              <div className="space-y-2">
                {output && <pre className="bg-slate-900 rounded p-3 text-xs text-slate-300 font-mono whitespace-pre-wrap">{output}</pre>}
                {issues.map((issue,i)=>(
                  <div key={i} className={`flex items-start gap-2 text-xs p-2 rounded bg-slate-900 border border-slate-800 ${severityColor[issue.severity]}`}>
                    <span className="font-bold shrink-0">L{issue.line}</span>
                    <span className="text-slate-300">{issue.message}</span>
                  </div>
                ))}
                {!output && issues.length===0 && <p className="text-xs text-slate-600 text-center mt-8">Run Validate or Compile to see output</p>}
              </div>
            )}
            {rightTab==='snippets' && (
              <div className="space-y-2">
                {snippets.length===0 && <p className="text-xs text-slate-600 text-center mt-8">Loading snippets…</p>}
                {snippets.map((s,i)=>(
                  <div key={i} className="bg-slate-900 border border-slate-800 rounded-lg p-2">
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-xs font-bold text-slate-300">{s.title}</span>
                      <button onClick={()=>insertSnippet(s.code)} className="px-1.5 py-0.5 bg-emerald-700 hover:bg-emerald-600 text-white text-[10px] rounded transition-colors flex items-center gap-0.5"><Zap className="w-2.5 h-2.5"/>Insert</button>
                    </div>
                    <pre className="text-[10px] text-slate-500 font-mono overflow-hidden" style={{maxHeight:40}}>{s.code.slice(0,100)}</pre>
                  </div>
                ))}
              </div>
            )}
            {rightTab==='events' && (
              <div className="space-y-3">
                {Object.keys(events).length===0 && <p className="text-xs text-slate-600 text-center mt-8">Loading events…</p>}
                {Object.entries(events).map(([cls, evts])=>(
                  <div key={cls}>
                    <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-widest mb-1">{cls}</div>
                    {(evts as string[]).map((ev,i)=>(
                      <button key={i} onClick={()=>insertSnippet(`Event ${ev}\n    ; TODO\nEndEvent`)}
                        className="block w-full text-left text-xs text-slate-300 hover:text-white hover:bg-slate-800 px-2 py-1 rounded font-mono transition-colors">
                        {ev}
                      </button>
                    ))}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
export default PapyrusIDE;
