"""
F4SE Plugin Scaffolder Service — port 8016
Generates ready-to-compile F4SE (Fallout 4 Script Extender) C++ plugin stubs
using Jinja2 templates.

F4SE GitHub: https://github.com/ianpatt/f4se
CommonLib-F4 (modern header-only F4SE SDK): https://github.com/Ryan-rsm-McKenzie/CommonLibF4

The service fills in:
  - Plugin version manifest (F4SE version, runtime version, plugin name/author)
  - CMakeLists.txt with vcpkg integration
  - main.cpp stub with the required F4SEPlugin_Query / F4SEPlugin_Load exports
  - Optional event hooks (OnMessage, OnCameraStateChanged, etc.)
  - Optional papyrus function registration scaffold
  - Optional MCM helper stub (F4SE MCM support)

All output is generated in-memory and returned as a file map so the React
component can write the tree to disk via the native `files` IPC.
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Optional, List, Dict
from fastapi import FastAPI
from pydantic import BaseModel

try:
    from jinja2 import Environment, BaseLoader, select_autoescape  # type: ignore
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

app = FastAPI()

# ── Jinja2 template strings ────────────────────────────────────────────────

_CMAKELISTS_TMPL = """\
cmake_minimum_required(VERSION 3.21)

# ── vcpkg toolchain (set VCPKG_ROOT env var before configuring) ────────────
if(DEFINED ENV{VCPKG_ROOT})
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
        CACHE STRING "" FORCE)
endif()

project({{ plugin_id }} VERSION {{ version_major }}.{{ version_minor }}.{{ version_patch }}
        LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)

# ── CommonLibF4 ─────────────────────────────────────────────────────────────
find_package(CommonLibF4 CONFIG REQUIRED)

# ── Source files ────────────────────────────────────────────────────────────
file(GLOB_RECURSE SOURCES src/*.cpp src/*.h)
add_library({{ plugin_id }} SHARED ${SOURCES})

target_include_directories({{ plugin_id }} PRIVATE src)
target_link_libraries({{ plugin_id }} PRIVATE CommonLibF4::CommonLibF4)

# ── Output: copy DLL to F4SE plugins folder after build ─────────────────────
set(F4SE_PLUGINS_DIR "$ENV{SKYRIM_MODS_DIR}/{{ plugin_name }}/F4SE/Plugins"
    CACHE PATH "Destination for the compiled plugin DLL")

add_custom_command(TARGET {{ plugin_id }} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${F4SE_PLUGINS_DIR}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "$<TARGET_FILE:{{ plugin_id }}>"
        "${F4SE_PLUGINS_DIR}/$<TARGET_FILE_NAME:{{ plugin_id }}>"
    COMMENT "Deploying ${project_name} to F4SE plugins folder"
)
"""

_MAIN_CPP_TMPL = """\
// {{ plugin_name }} — F4SE plugin
// Author : {{ author }}
// Version: {{ version_major }}.{{ version_minor }}.{{ version_patch }}
//
// Generated by Mossy Desktop AI — F4SE Scaffolder
// Reference: https://github.com/ianpatt/f4se

#include <F4SE/F4SE.h>
#include <RE/Fallout.h>
{% if has_papyrus %}
#include <F4SE/API.h>
{% endif %}

namespace logger = SKSE::log;  // CommonLibF4 re-exports SKSE log helpers

// ── Forward declarations ─────────────────────────────────────────────────
{% if has_papyrus %}
static void RegisterPapyrusFunctions(RE::BSScript::IVirtualMachine* vm);
{% endif %}
{% for hook in hooks %}
static void On{{ hook }}();
{% endfor %}

// ── Plugin query (called by F4SE to decide whether to load) ──────────────
extern "C" __declspec(dllexport)
F4SEPluginVersionData F4SEPlugin_Version = {
    .dataVersion = F4SEPluginVersionData::kVersion,
    .pluginVersion = REL::Version{ {{ version_major }}, {{ version_minor }}, {{ version_patch }}, 0 },
    .pluginName    = "{{ plugin_name }}",
    .author        = "{{ author }}",
    .usesAddressLibrary = {{ "true" if use_address_library else "false" }},
    .compatibleVersions = { RUNTIME_VERSION_1_10_984 },  // update as needed
};

// ── Plugin load (called after F4SE has verified the plugin) ──────────────
extern "C" __declspec(dllexport)
bool F4SEPlugin_Load(const F4SE::LoadInterface* f4se)
{
    F4SE::Init(f4se);

    // Set up log file: <Documents>/My Games/Fallout4/F4SE/{{ plugin_id }}.log
    F4SE::AllocTrampoline({{ trampoline_size }});

    logger::init();
    logger::info("{{ plugin_name }} v{}.{}.{} loaded",
        {{ version_major }}, {{ version_minor }}, {{ version_patch }});

    const auto papyrusInterface = F4SE::GetPapyrusInterface();
{% if has_papyrus %}
    if (papyrusInterface) {
        papyrusInterface->Register(RegisterPapyrusFunctions);
        logger::info("Papyrus functions registered");
    } else {
        logger::warn("Papyrus interface unavailable — skipping registration");
    }
{% endif %}

    const auto messagingInterface = F4SE::GetMessagingInterface();
    if (messagingInterface) {
        messagingInterface->RegisterListener(
            [](F4SE::MessagingInterface::Message* msg) {
                switch (msg->type) {
                    case F4SE::MessagingInterface::kGameDataReady:
                        logger::info("Game data ready");
{% for hook in hooks %}
                        On{{ hook }}();
{% endfor %}
                        break;
                    default:
                        break;
                }
            });
    }

    return true;
}

// ── Hook implementations ─────────────────────────────────────────────────
{% for hook in hooks %}
void On{{ hook }}()
{
    logger::info("On{{ hook }} called");
    // TODO: implement {{ hook }} logic here
}

{% endfor %}
{% if has_papyrus %}
// ── Papyrus function bindings ─────────────────────────────────────────────

// Example Papyrus-exposed function:
//   Function MyFunc(int akArg) Global Native
static int MyFunc(RE::BSScript::IVirtualMachine*, RE::VMStackID,
                  RE::TESObjectREFR*, int akArg)
{
    logger::info("MyFunc called with arg={}", akArg);
    return akArg * 2;
}

void RegisterPapyrusFunctions(RE::BSScript::IVirtualMachine* vm)
{
    // vm->RegisterFunction("MyFunc", "{{ plugin_name }}", MyFunc);
    logger::info("RegisterPapyrusFunctions — add vm->RegisterFunction calls here");
}
{% endif %}
"""

_VCPKG_JSON_TMPL = """\
{
  "name": "{{ plugin_id | lower | replace('_', '-') }}",
  "version": "{{ version_major }}.{{ version_minor }}.{{ version_patch }}",
  "dependencies": [
    {
      "name": "commonlibf4",
      "version>=": "1.0.0"
    }
  ]
}
"""

_README_TMPL = """\
# {{ plugin_name }}

**Author**: {{ author }}
**Version**: {{ version_major }}.{{ version_minor }}.{{ version_patch }}
**F4SE Plugin** for Fallout 4

## Building

### Requirements
- Visual Studio 2022 (MSVC v143+, C++23)
- [CMake 3.21+](https://cmake.org/)
- [vcpkg](https://github.com/microsoft/vcpkg)
- [CommonLibF4](https://github.com/Ryan-rsm-McKenzie/CommonLibF4) (installed via vcpkg)

### Steps
```powershell
# 1. Clone + bootstrap vcpkg (one-time)
git clone https://github.com/microsoft/vcpkg
.\\vcpkg\\bootstrap-vcpkg.bat

# 2. Set environment variables
$env:VCPKG_ROOT = "C:\\vcpkg"
$env:SKYRIM_MODS_DIR = "C:\\MO2\\mods"   # adjust to your mod manager staging dir

# 3. Configure
cmake -B build -S . --preset vs2022-windows

# 4. Build
cmake --build build --config Release
```

The compiled `{{ plugin_id }}.dll` will be copied to  
`%SKYRIM_MODS_DIR%/{{ plugin_name }}/F4SE/Plugins/` automatically.

## License
MIT
"""

_CMAKE_PRESET_TMPL = """\
{
  "version": 3,
  "configurePresets": [
    {
      "name": "vs2022-windows",
      "generator": "Visual Studio 17 2022",
      "architecture": "x64",
      "binaryDir": "${sourceDir}/build",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "VCPKG_TARGET_TRIPLET": "x64-windows-static-md"
      }
    }
  ]
}
"""

# ── Jinja2 environment ────────────────────────────────────────────────────

def _make_env() -> Optional[object]:
    if not JINJA2_AVAILABLE:
        return None
    return Environment(
        loader=BaseLoader(),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def _render(env, template_str: str, ctx: dict) -> str:
    tmpl = env.from_string(template_str)
    return tmpl.render(**ctx)


def _slugify(name: str) -> str:
    """Convert display name to a safe C identifier / filename stem."""
    s = re.sub(r"[^\w]", "_", name)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "MyPlugin"


# ── Request / response models ─────────────────────────────────────────────

class ScaffoldRequest(BaseModel):
    plugin_name: str
    author: str = "Unknown"
    version_major: int = 1
    version_minor: int = 0
    version_patch: int = 0
    hooks: List[str] = []          # e.g. ["DataLoaded", "NewGame", "LoadGame"]
    has_papyrus: bool = False      # include Papyrus registration scaffold
    use_address_library: bool = True
    trampoline_size: int = 64
    output_dir: Optional[str] = None  # if set, write files to disk


# ── Endpoints ─────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "f4se",
        "jinja2_available": JINJA2_AVAILABLE,
    }


@app.post("/scaffold")
def scaffold(req: ScaffoldRequest):
    """Generate a complete F4SE plugin project scaffold."""
    if not JINJA2_AVAILABLE:
        return {
            "status": "unavailable",
            "message": "jinja2 is not installed. Run: pip install jinja2",
        }

    env = _make_env()
    if env is None:
        return {"status": "error", "message": "Failed to create Jinja2 environment"}

    plugin_id = _slugify(req.plugin_name)
    ctx = {
        "plugin_name":     req.plugin_name,
        "plugin_id":       plugin_id,
        "author":          req.author,
        "version_major":   req.version_major,
        "version_minor":   req.version_minor,
        "version_patch":   req.version_patch,
        "hooks":           req.hooks,
        "has_papyrus":     req.has_papyrus,
        "use_address_library": req.use_address_library,
        "trampoline_size": req.trampoline_size,
    }

    files: Dict[str, str] = {
        "CMakeLists.txt":      _render(env, _CMAKELISTS_TMPL, ctx),
        "CMakePresets.json":   _render(env, _CMAKE_PRESET_TMPL, ctx),
        "vcpkg.json":          _render(env, _VCPKG_JSON_TMPL, ctx),
        "README.md":           _render(env, _README_TMPL, ctx),
        f"src/main.cpp":       _render(env, _MAIN_CPP_TMPL, ctx),
    }

    # Optionally write to disk — guard against path traversal in template keys
    written: List[str] = []
    errors: List[str] = []
    if req.output_dir:
        base = Path(req.output_dir).resolve()
        for rel_path, content in files.items():
            try:
                # Resolve the destination and ensure it stays inside base
                dest = (base / rel_path).resolve()
                if not str(dest).startswith(str(base)):
                    errors.append(f"{rel_path}: rejected (path traversal)")
                    continue
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content, encoding="utf-8")
                written.append(str(dest))
            except OSError as e:
                errors.append(f"{rel_path}: write error")

    return {
        "status": "ok",
        "plugin_name": req.plugin_name,
        "plugin_id": plugin_id,
        "files": files,
        "written": written,
        "errors": errors,
    }


@app.get("/hook-catalog")
def hook_catalog():
    """List the common F4SE/CommonLibF4 hooks available as scaffold options."""
    return {
        "status": "ok",
        "hooks": [
            {"name": "DataLoaded",            "description": "Called when all game data (ESPs, BSAs) is loaded"},
            {"name": "NewGame",               "description": "Called when the player starts a new game"},
            {"name": "LoadGame",              "description": "Called when a saved game is loaded"},
            {"name": "SaveGame",              "description": "Called before a game is saved"},
            {"name": "DeleteGame",            "description": "Called when a save file is deleted"},
            {"name": "InputLoaded",           "description": "Called after input handlers are registered"},
            {"name": "PostLoadGame",          "description": "Called after a game finishes loading (actor data ready)"},
            {"name": "CameraStateChanged",    "description": "Fires when camera state transitions (first/third person)"},
            {"name": "CrosshairRefChanged",   "description": "Fires when the crosshair target changes"},
            {"name": "ActorKill",             "description": "Fires when any actor is killed"},
            {"name": "ItemHarvested",         "description": "Fires when the player harvests an item"},
            {"name": "LevelIncrease",         "description": "Fires on player level-up"},
            {"name": "LocationDiscovery",     "description": "Fires when a new map location is discovered"},
            {"name": "ShoutAttack",           "description": "Fires when the player uses a shout"},
            {"name": "MagicEffectApply",      "description": "Fires when a magic effect is applied to an actor"},
            {"name": "ObjectGrab",            "description": "Fires when the player grabs an object"},
            {"name": "ObjectRelease",         "description": "Fires when the player releases a grabbed object"},
        ],
    }


@app.get("/templates")
def list_templates():
    """List available scaffold templates."""
    return {
        "status": "ok",
        "templates": [
            {
                "id":          "basic",
                "name":        "Basic Plugin",
                "description": "Minimal F4SE plugin with version manifest and load hook",
                "defaults": {
                    "hooks": [],
                    "has_papyrus": False,
                    "use_address_library": True,
                },
            },
            {
                "id":          "papyrus_native",
                "name":        "Papyrus Native Functions",
                "description": "Plugin that registers new native Papyrus functions callable from scripts",
                "defaults": {
                    "hooks": ["DataLoaded"],
                    "has_papyrus": True,
                    "use_address_library": True,
                },
            },
            {
                "id":          "event_listener",
                "name":        "Event Listener",
                "description": "Plugin that reacts to in-game events (kill, loot, level-up, etc.)",
                "defaults": {
                    "hooks": ["DataLoaded", "ActorKill", "ItemHarvested", "LevelIncrease"],
                    "has_papyrus": False,
                    "use_address_library": True,
                },
            },
            {
                "id":          "full",
                "name":        "Full-Featured Plugin",
                "description": "Event listener + Papyrus native functions + Address Library",
                "defaults": {
                    "hooks": ["DataLoaded", "NewGame", "LoadGame", "SaveGame"],
                    "has_papyrus": True,
                    "use_address_library": True,
                },
            },
        ],
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8016)
