"""
TripoSR 3D Service — port 8007
3D mesh generation from images using TripoSR (optional) or stub cube OBJ.
"""
import base64
import io
import os
import time
from pathlib import Path
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional

app = FastAPI()

try:
    import torch
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False

try:
    import tsr
    TRIPOSR_AVAILABLE = True
except ImportError:
    TRIPOSR_AVAILABLE = False

OUTPUT_DIR = Path("data/triposr_outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

STUB_CUBE_OBJ = """\
# Stub cube OBJ — generated by Mossy TripoSR service (TripoSR not installed)
# Install: pip install git+https://github.com/VAST-AI-Research/TripoSR.git
o Cube
v  1.0  1.0 -1.0
v  1.0 -1.0 -1.0
v  1.0  1.0  1.0
v  1.0 -1.0  1.0
v -1.0  1.0 -1.0
v -1.0 -1.0 -1.0
v -1.0  1.0  1.0
v -1.0 -1.0  1.0
vn  0.0  1.0  0.0
vn  0.0  0.0  1.0
vn -1.0  0.0  0.0
vn  0.0 -1.0  0.0
vn  1.0  0.0  0.0
vn  0.0  0.0 -1.0
s off
f 1//5 2//5 4//5 3//5
f 5//1 7//1 8//1 6//1
f 1//6 5//6 6//6 2//6
f 2//4 6//4 8//4 4//4
f 4//2 8//2 7//2 3//2
f 5//3 1//3 3//3 7//3
"""


@app.get("/health")
async def health():
    return {
        "status": "healthy",
        "service": "triposr-3d",
        "triposr_available": TRIPOSR_AVAILABLE,
        "torch_available": TORCH_AVAILABLE,
    }


class GenerateMeshRequest(BaseModel):
    image_base64: str
    output_format: Optional[str] = "obj"
    resolution: Optional[int] = 128


@app.post("/generate-mesh")
async def generate_mesh(req: GenerateMeshRequest):
    start = time.time()

    if not TRIPOSR_AVAILABLE:
        mesh_b64 = base64.b64encode(STUB_CUBE_OBJ.encode()).decode()
        return {
            "status": "stub",
            "mesh_base64": mesh_b64,
            "format": "obj",
            "vertex_count": 8,
            "face_count": 6,
            "generation_time": round(time.time() - start, 3),
            "message": (
                "TripoSR is not installed. To install:\n"
                "  pip install git+https://github.com/VAST-AI-Research/TripoSR.git\n"
                "Returning stub cube OBJ."
            ),
        }

    try:
        import torch
        from PIL import Image

        img_data = base64.b64decode(req.image_base64)
        img = Image.open(io.BytesIO(img_data)).convert("RGB")

        model = tsr.TSR.from_pretrained(
            "stabilityai/TripoSR",
            config_name="config.yaml",
            weight_name="model.ckpt",
        )
        model.renderer.set_chunk_size(8192)
        if TORCH_AVAILABLE and torch.cuda.is_available():
            model = model.cuda()
        model.eval()

        with torch.no_grad():
            scene_codes = model([img], device="cuda" if torch.cuda.is_available() else "cpu")
            meshes = model.extract_mesh(scene_codes, resolution=req.resolution or 128)

        mesh = meshes[0]
        buf = io.BytesIO()
        mesh.export(buf, file_type=req.output_format or "obj")
        mesh_b64 = base64.b64encode(buf.getvalue()).decode()

        return {
            "status": "ok",
            "mesh_base64": mesh_b64,
            "format": req.output_format or "obj",
            "vertex_count": len(mesh.vertices),
            "face_count": len(mesh.faces),
            "generation_time": round(time.time() - start, 3),
        }
    except Exception as e:
        mesh_b64 = base64.b64encode(STUB_CUBE_OBJ.encode()).decode()
        return {
            "status": "error",
            "message": f"Mesh generation error: {type(e).__name__}",
            "mesh_base64": mesh_b64,
            "format": "obj",
            "vertex_count": 8,
            "face_count": 6,
            "generation_time": round(time.time() - start, 3),
        }


@app.get("/outputs")
async def list_outputs():
    try:
        files = list(OUTPUT_DIR.glob("*.obj")) + list(OUTPUT_DIR.glob("*.glb"))
        return {
            "status": "ok",
            "files": [
                {
                    "name": f.name,
                    "path": str(f),
                    "size_bytes": f.stat().st_size,
                    "modified": f.stat().st_mtime,
                }
                for f in sorted(files, key=lambda x: x.stat().st_mtime, reverse=True)
            ],
        }
    except Exception as e:
        return {"status": "error", "message": f"Output listing error: {type(e).__name__}", "files": []}


class ExportBlenderRequest(BaseModel):
    mesh_base64: str
    mesh_name: str


@app.post("/export-blender")
async def export_blender(req: ExportBlenderRequest):
    try:
        mesh_data = base64.b64decode(req.mesh_base64)
        safe_name = "".join(c for c in req.mesh_name if c.isalnum() or c in ("_", "-"))
        if not safe_name:
            safe_name = "mesh_export"
        # Resolve output path and verify it stays within OUTPUT_DIR
        out_path = (OUTPUT_DIR / f"{safe_name}.obj").resolve()
        if not str(out_path).startswith(str(OUTPUT_DIR.resolve())):
            return {"status": "error", "message": "Invalid mesh name"}
        out_path.write_bytes(mesh_data)
        return {
            "status": "ok",
            "file_path": str(out_path),
            "blender_command": f"blender --python-expr \"import bpy; bpy.ops.import_scene.obj(filepath='{out_path}')\"",
        }
    except Exception as e:
        return {"status": "error", "message": f"Export failed: {type(e).__name__}"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8007)
